version: "3.7"
services:
  webapp:
    image: webgoat/webgoat-7.1
    ports:
      - "8080:8080"

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  node:
    image: selenium/node-chrome
    shm_size: '2gb'
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: "1360"
      SCREEN_HEIGHT: "1020"
    depends_on:
      - hub
    links:
      - hub
      - webapp