version: "3.7"
services:
  webgoat:
    build:
      context: .
      dockerfile: Dockerfile.webgoat
    container_name: webgoat
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Prague"

  hub:
    image: selenium/hub:4.0.0-beta-4-20210608
    container_name: hub
    ports:
      - "4444:4444"
    environment:
      TZ: "Europe/Prague"

  chrome1:
    image: selenium/node-chrome:4.0.0-beta-4-20210608
    container_name: chrome1
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SCREEN_WIDTH: "1920"
      SCREEN_HEIGHT: "1080"
      TZ: "Europe/Prague"
    depends_on:
      - hub
    links:
      - hub
      - webgoat

  chrome2:
    image: selenium/node-chrome:4.0.0-beta-4-20210608
    container_name: chrome2
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SCREEN_WIDTH: "1920"
      SCREEN_HEIGHT: "1080"
      TZ: "Europe/Prague"
    depends_on:
      - hub
    links:
      - hub
      - webgoat
