version: "3.7"
services:
  webgoat:
    image: webgoat/webgoat-7.1
    container_name: webgoat
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Prague"

  hub:
    image: selenium/hub
    container_name: hub
    ports:
      - "4444:4444"
    environment:
      TZ: "Europe/Prague"

  chrome1:
    image: selenium/node-chrome
    container_name: chrome1
    shm_size: '2gb'
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: "1920"
      SCREEN_HEIGHT: "1080"
      TZ: "Europe/Prague"
    depends_on:
      - hub
    links:
      - hub
      - webgoat

  chrome2:
    image: selenium/node-chrome
    container_name: chrome2
    shm_size: '2gb'
    environment:
      HUB_HOST: hub
      SCREEN_WIDTH: "1920"
      SCREEN_HEIGHT: "1080"
      TZ: "Europe/Prague"
    depends_on:
      - hub
    links:
      - hub
      - webgoat
